CREATE TABLE IF NOT EXISTS postits (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    color VARCHAR(7) DEFAULT '#FFFFFF',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_postits_color ON postits(color);
